export interface NorwayPlace {
  id: string
  name: string
  shortDescription: string
  longDescription: string
  category: string
  distanceFromBergen: number
  bestSeason: string
  coordinates: { lat: number; lng: number }
  crowdLevel: "Popular" | "Moderate" | "Low Crowds"
  images: string[]
  priority: "Must Do" | "Highly Recommended" | "Nice to Have"
  zone: string
  driveFromBergen: string
  familyRating: string
  vanNote?: string
  highlights: string[]
}

// All images use Wikimedia Commons CDN — publicly accessible, no hotlink restrictions
const WM = (file: string) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=800`

export const places: NorwayPlace[] = [
  {
    id: "bergen-bryggen",
    name: "Bergen — Bryggen & Fløibanen",
    shortDescription: "UNESCO-listed colourful Hanseatic wharf and funicular to panoramic mountain views.",
    longDescription:
      "Bergen's colourful Bryggen wharf is one of the most photographed sights in Scandinavia — a UNESCO World Heritage Site since 1979. The Fløibanen funicular runs in 5 minutes to panoramic views from Mt. Fløyen. A perfect half-day before picking up the camper, with the roadsurfer depot only 15 min away at Blomsterdalen.",
    category: "Cultural",
    distanceFromBergen: 0,
    bestSeason: "Year-round",
    coordinates: { lat: 60.3976, lng: 5.3242 },
    crowdLevel: "Popular",
    images: [
      WM("Bryggen Bergen the German Wharf.JPG"),
      WM("Bryggen,_Bergen3.JPG"),
      WM("Bergen_from_Fløyen_in_September.jpg"),
      WM("Bergen_fish_market_2009.jpg"),
      WM("Fløibanen_in_Bergen.jpg"),
    ],
    priority: "Must Do",
    zone: "Bergen City",
    driveFromBergen: "0 — pickup zone",
    familyRating: "⭐⭐⭐⭐⭐",
    highlights: [
      "Bryggen wharf — UNESCO medieval wooden houses along the harbour",
      "Fløibanen funicular — 5-min ride to Mt. Fløyen, kids love it",
      "Fish market (Fisketorget) — excellent fresh seafood lunch",
      "No campervan parking in centre — visit before or after pickup",
    ],
  },
  {
    id: "steindalsfossen",
    name: "Steindalsfossen — Walk-Behind Waterfall",
    shortDescription: "A unique waterfall near Norheimsund where a safe path lets you walk behind the roaring curtain of water.",
    longDescription:
      "Near Norheimsund on the western Hardangerfjord, a safe path leads directly behind the roaring curtain of water. Completely free, 5-minute walk from the car park. Perfect first stop after leaving Bergen.",
    category: "Nature",
    distanceFromBergen: 90,
    bestSeason: "April - October",
    coordinates: { lat: 60.3761, lng: 6.1394 },
    crowdLevel: "Low Crowds",
    images: [
      WM("Steinsdalsfossen.jpg"),
      WM("Steinsdalsfossen_-_stien_bak_fossen.jpg"),
      WM("Hardangerfjorden_from_Hardangerbrua.jpg"),
      WM("Norheimsund_-_panoramio.jpg"),
      WM("Hardangerfjord.jpg"),
    ],
    priority: "Highly Recommended",
    zone: "Hardangerfjord",
    driveFromBergen: "1.5h SE",
    familyRating: "⭐⭐⭐⭐⭐",
    highlights: [
      "Walk directly behind the waterfall — completely safe path",
      "Free, 5-minute walk from parking",
      "Great for kids — genuinely exciting and totally safe",
      "Combine with the Hardangerfjord scenic drive on the same day",
    ],
  },
  {
    id: "hardangerfjord-drive",
    name: "Hardangerfjord Drive + Låtefossen",
    shortDescription: "Norway's second-longest fjord with lush orchards, fruit farms and the dramatic Låtefossen twin falls.",
    longDescription:
      "Norway's second-longest fjord threads through lush orchards and fruit farms. June brings dense greenery and gushing waterfalls. The Låtefossen twin falls are visible right from the road near Odda — zero walking required.",
    category: "Fjord",
    distanceFromBergen: 120,
    bestSeason: "May - September",
    coordinates: { lat: 60.1208, lng: 6.5481 },
    crowdLevel: "Moderate",
    images: [
      WM("Låtefossen.jpg"),
      WM("Hardangerfjorden_from_Hardangerbrua.jpg"),
      WM("Hardangerfjord.jpg"),
      WM("Ulvik_Norway.jpg"),
      WM("Eidfjord_Norway.jpg"),
    ],
    priority: "Highly Recommended",
    zone: "Hardangerfjord",
    driveFromBergen: "1.5–2h SE",
    familyRating: "⭐⭐⭐⭐⭐",
    highlights: [
      "Låtefossen — twin waterfalls visible straight from the road",
      "Fruit farm stops — cider, juice, early strawberries in June",
      "Ulvik village — tiny, peaceful, beautiful fjord setting",
      "Excellent campervan roads throughout the region",
    ],
  },
  {
    id: "voringsfossen",
    name: "Vøringsfossen — 182m Plunge",
    shortDescription: "Norway's most famous waterfall — a 182-metre free-fall into the dramatic Måbødalen gorge.",
    longDescription:
      "Norway's most famous waterfall plunges 182 metres into the Måbødalen gorge. Short walk from the viewpoint car park. Arrive before 10am to beat the tour buses. Eidfjord village is nearby for a lunch stop.",
    category: "Nature",
    distanceFromBergen: 165,
    bestSeason: "May - September",
    coordinates: { lat: 60.4003, lng: 7.2144 },
    crowdLevel: "Popular",
    images: [
      WM("Vøringsfossen.jpg"),
      WM("Vøringsfossen,_Eidfjord,_Hordaland,_Norway_(waterfall).jpg"),
      WM("Voringsfoss-norway.jpg"),
      WM("Eidfjord_Norway.jpg"),
      WM("Hardangervidda_national_park.jpg"),
    ],
    priority: "Must Do",
    zone: "Hardangerfjord",
    driveFromBergen: "2.5h SE via Eidfjord",
    familyRating: "⭐⭐⭐⭐⭐",
    vanNote: "⚠️ Approach roads near Eidfjord are narrow — take it slowly",
    highlights: [
      "182m free-fall — one of Europe's most dramatic waterfalls",
      "5–10 min walk from car park to viewpoint",
      "Eidfjord village nearby for lunch",
      "Gateway to Hardangervidda plateau above",
    ],
  },
  {
    id: "rosendal",
    name: "Rosendal — Barony & Rose Gardens",
    shortDescription: "Norway's only barony — a 17th-century manor with rose gardens and Folgefonna glacier views above.",
    longDescription:
      "Norway's only barony — a 17th-century manor house with beautiful rose gardens and the Folgefonna glacier visible above the village. Very quiet, charming, and almost completely un-touristy.",
    category: "Cultural",
    distanceFromBergen: 140,
    bestSeason: "June - August",
    coordinates: { lat: 59.9827, lng: 6.0033 },
    crowdLevel: "Low Crowds",
    images: [
      WM("Baroniet_Rosendal.jpg"),
      WM("Rosendal_Norway.jpg"),
      WM("Folgefonna_from_Rosendal.jpg"),
      WM("Hardangerfjord.jpg"),
      WM("Hardangerfjorden_from_Hardangerbrua.jpg"),
    ],
    priority: "Nice to Have",
    zone: "Hardangerfjord",
    driveFromBergen: "2–2.5h SE",
    familyRating: "⭐⭐⭐⭐",
    highlights: [
      "Baroniet Rosendal — historic manor with rose gardens",
      "Folgefonna glacier visible on the hillside above",
      "Almost no tourists — genuinely peaceful",
      "Best paired with overnight in Hardanger",
    ],
  },
  {
    id: "tvindefossen",
    name: "Tvindefossen — Roadside Waterfall",
    shortDescription: "A tall, graceful waterfall right beside the road — park the camper, walk 2 minutes.",
    longDescription:
      "A tall, graceful waterfall right beside the road between Voss and Flåm. Park the camper, walk 2 minutes. Unbeatable effort-to-reward ratio — one of the best quick stops on the whole trip.",
    category: "Nature",
    distanceFromBergen: 95,
    bestSeason: "April - October",
    coordinates: { lat: 60.7271, lng: 6.4494 },
    crowdLevel: "Low Crowds",
    images: [
      WM("Tvindefossen.jpg"),
      WM("Tvindefossen_waterfall_Norway.jpg"),
      WM("Voss_municipality.jpg"),
      WM("Stalheimskleiva_Norway.jpg"),
      WM("Vossevangen_Norway.jpg"),
    ],
    priority: "Highly Recommended",
    zone: "Voss & Flåm",
    driveFromBergen: "1.5h NE",
    familyRating: "⭐⭐⭐⭐⭐",
    highlights: [
      "2-minute walk from roadside parking",
      "Tall multi-stream fall with a beautiful wide base",
      "Perfect stretch stop on the Bergen–Flåm drive",
      "Almost no crowds",
    ],
  },
  {
    id: "voss",
    name: "Voss — Gondola & Town",
    shortDescription: "Norway's adventure capital — the Voss Gondol rises 818m for panoramic views and a mountain restaurant.",
    longDescription:
      "Norway's adventure capital. The Voss Gondol rises 818m for panoramic views and a restaurant at the top. Good supermarkets make this a smart resupply stop. Lake Vangsvatnet is lovely for a picnic.",
    category: "Adventure",
    distanceFromBergen: 100,
    bestSeason: "Year-round",
    coordinates: { lat: 60.6278, lng: 6.4183 },
    crowdLevel: "Moderate",
    images: [
      WM("Voss_gondola_Norway.jpg"),
      WM("Vangsvatnet,_Voss.jpg"),
      WM("Vossevangen_Norway.jpg"),
      WM("Voss_municipality.jpg"),
      WM("Hardangerfjord.jpg"),
    ],
    priority: "Highly Recommended",
    zone: "Voss & Flåm",
    driveFromBergen: "1.5h NE",
    familyRating: "⭐⭐⭐⭐",
    highlights: [
      "Voss Gondol — 818m altitude, restaurant at top",
      "Lake Vangsvatnet — lakeside picnic spot",
      "Good supermarkets — excellent resupply point",
      "Gondola is the star attraction for a 5-year-old",
    ],
  },
  {
    id: "flam-railway",
    name: "Flåm + Flåmsbana Railway",
    shortDescription: "One of the world's most scenic railways — 20km through mountain valleys past thundering waterfalls.",
    longDescription:
      "The Flåmsbana is one of the world's most scenic railways — 20km through mountain valleys past thundering waterfalls. The train pauses mid-journey at Kjosfossen waterfall. Kids are absolutely transfixed. Flåm village sits at the head of the gorgeous Aurlandsfjord.",
    category: "Railway",
    distanceFromBergen: 170,
    bestSeason: "Year-round",
    coordinates: { lat: 60.8634, lng: 7.1183 },
    crowdLevel: "Popular",
    images: [
      WM("Flåmsbana.jpg"),
      WM("Flam_railway_Myrdal.jpg"),
      WM("Kjosfossen_waterfall.jpg"),
      WM("Aurlandsfjord.jpg"),
      WM("Flam_Norway.jpg"),
    ],
    priority: "Must Do",
    zone: "Voss & Flåm",
    driveFromBergen: "2h NE",
    familyRating: "⭐⭐⭐⭐⭐",
    highlights: [
      "Flåmsbana — world-famous scenic railway through fjord valley",
      "Train pauses at Kjosfossen waterfall for photo stop",
      "Fjord boat trip from the village into Aurlandsfjord",
      "⚠️ Cruise ships arrive daily — go first thing in the morning",
    ],
  },
  {
    id: "stegastein",
    name: "Aurland + Stegastein Viewpoint",
    shortDescription: "A cantilevered platform jutting 30m out from a mountainside at 650m altitude — straight down to the Aurlandsfjord.",
    longDescription:
      "Stegastein is a cantilevered platform jutting 30m out from a mountainside at 650m altitude, looking straight down at the Aurlandsfjord. Reached via the spectacular Aurlandsfjellet Snow Road.",
    category: "Viewpoint",
    distanceFromBergen: 175,
    bestSeason: "May - October",
    coordinates: { lat: 60.9008, lng: 7.1831 },
    crowdLevel: "Moderate",
    images: [
      WM("Stegastein.jpg"),
      WM("Aurlandsfjellet.jpg"),
      WM("Aurlandsfjord.jpg"),
      WM("Aurland_Norway.jpg"),
      WM("Snow_Road_Aurlandsfjellet.jpg"),
    ],
    priority: "Must Do",
    zone: "Voss & Flåm",
    driveFromBergen: "2h NE",
    familyRating: "⭐⭐⭐⭐⭐",
    vanNote: "⚠️ Snow Road is narrow — doable in 5.4m camper, take it slowly",
    highlights: [
      "Platform extends 30m over the fjord — spectacular",
      "Drive via Aurlandsfjellet (Snow Road) — stunning mountain plateau",
      "Aurland village below — quiet, charming overnight stop",
      "Electric minibus from Flåm if you prefer not to drive",
    ],
  },
  {
    id: "naeroyfjord",
    name: "Nærøyfjord Ferry",
    shortDescription: "UNESCO-listed — one of the world's narrowest fjords. Near-vertical walls with waterfalls on both sides.",
    longDescription:
      "UNESCO-listed alongside Geirangerfjord — one of the world's narrowest fjords. The public ferry from Gudvangen to Flåm passes through near-vertical walls with waterfalls on both sides. Two hours of pure drama on the water.",
    category: "Fjord",
    distanceFromBergen: 165,
    bestSeason: "April - October",
    coordinates: { lat: 60.9166, lng: 6.8906 },
    crowdLevel: "Moderate",
    images: [
      WM("Nærøyfjord.jpg"),
      WM("Naeroyfjord_norway_UNESCO.jpg"),
      WM("Nærøyfjorden_seen_from_Rimstigen.jpg"),
      WM("Gudvangen_Nærøyfjord.jpg"),
      WM("Aurlandsfjord.jpg"),
    ],
    priority: "Must Do",
    zone: "Nærøyfjord",
    driveFromBergen: "2h NE",
    familyRating: "⭐⭐⭐⭐⭐",
    highlights: [
      "Walls rise nearly vertically — barely 250m wide at narrowest",
      "Waterfalls cascade from both sides throughout",
      "Ferry carries campervans — or park and walk on",
      "Take the public Lustraabaten ferry for a quieter experience",
    ],
  },
  {
    id: "undredal",
    name: "Undredal — Tiny Village & Goat Cheese",
    shortDescription: "80 residents, Scandinavia's smallest stave church (1147 AD), and Norway's best brown goat cheese.",
    longDescription:
      "80 residents, goats outnumbering people 5:1, and home to Scandinavia's smallest stave church (built 1147, only 40 seats). Also one of the inspirations for Disney's Frozen village of Arendelle. The brown goat cheese here is legendary.",
    category: "Cultural",
    distanceFromBergen: 168,
    bestSeason: "May - September",
    coordinates: { lat: 60.9456, lng: 7.0781 },
    crowdLevel: "Low Crowds",
    images: [
      WM("Undredal_village_Nærøyfjord.jpg"),
      WM("Undredal_Stavkyrkje.jpg"),
      WM("Undredal_stave_church.jpg"),
      WM("Nærøyfjord.jpg"),
      WM("Naeroyfjord_norway_UNESCO.jpg"),
    ],
    priority: "Highly Recommended",
    zone: "Nærøyfjord",
    driveFromBergen: "2h NE",
    familyRating: "⭐⭐⭐⭐⭐",
    vanNote: "Reached via steep winding road off E16 — fine for your camper",
    highlights: [
      "Scandinavia's smallest stave church — built 1147, still in use",
      "Best brunost (brown goat cheese) in Norway",
      "Brown cheese ice cream — kids love it",
      "5 goats to every 1 human",
    ],
  },
  {
    id: "gudvangen-vikings",
    name: "Gudvangen — Viking Village",
    shortDescription: "A recreated Viking village (Njardarheimr) at the dramatic head of the Nærøyfjord valley.",
    longDescription:
      "A recreated Viking village (Njardarheimr) at the dramatic head of the Nærøyfjord valley. Ax throwing, archery, costumed re-enactors and Viking banquets — one of Norway's most hands-on family experiences.",
    category: "Cultural",
    distanceFromBergen: 155,
    bestSeason: "May - September",
    coordinates: { lat: 60.8783, lng: 6.8347 },
    crowdLevel: "Moderate",
    images: [
      WM("Gudvangen_Norway.jpg"),
      WM("Njardarheimr.jpg"),
      WM("Nærøyfjord.jpg"),
      WM("Gudvangen_fjord.jpg"),
      WM("Nærøyfjorden_seen_from_Rimstigen.jpg"),
    ],
    priority: "Highly Recommended",
    zone: "Nærøyfjord",
    driveFromBergen: "2h NE",
    familyRating: "⭐⭐⭐⭐⭐",
    highlights: [
      "Ax throwing and archery — supervised, suitable for kids",
      "Costumed re-enactors living as Vikings — very immersive",
      "Viking-style food and mead hall",
      "Spectacular setting at the end of the Nærøyfjord valley",
    ],
  },
  {
    id: "borgund-stave-church",
    name: "Borgund Stave Church + Lærdalsøyri",
    shortDescription: "Norway's best-preserved stave church (c.1180) with iconic dragon-head rooftops — zero detour on the E16.",
    longDescription:
      "Norway's best-preserved stave church, built c.1180 — the iconic dragon-head rooftops. Zero-detour stop on the E16. Lærdalsøyri old town next door has 200 beautifully preserved 18th-century wooden houses.",
    category: "Cultural",
    distanceFromBergen: 200,
    bestSeason: "May - September",
    coordinates: { lat: 61.0467, lng: 7.7008 },
    crowdLevel: "Moderate",
    images: [
      WM("Borgund_stave_church.jpg"),
      WM("Borgund_stavkirke.jpg"),
      WM("Laerdal_old_town.jpg"),
      WM("Borgund_stave_church_roof.jpg"),
      WM("Laerdalsoyri.jpg"),
    ],
    priority: "Highly Recommended",
    zone: "Voss & Flåm",
    driveFromBergen: "3h NE (on E16 route)",
    familyRating: "⭐⭐⭐⭐",
    highlights: [
      "Best-preserved stave church in Norway — c.1180 AD, dragon-head finials",
      "Lærdalsøyri — 200 painted 18th-century wooden houses",
      "Zero extra driving — directly on the E16 Bergen→Flåm route",
      "30–45 min total stop — excellent value",
    ],
  },
  {
    id: "balestrand",
    name: "Balestrand — Quiet Sognefjord Village",
    shortDescription: "A charming, unhurried fjord village with Viking burial mounds and the historic Kviknes Hotel (1877).",
    longDescription:
      "A charming, unhurried fjord village on the north shore of Sognefjord. Viking burial mounds, apple orchards, and the historic Kviknes Hotel (1877). A perfect antidote to Flåm crowds.",
    category: "Fjord",
    distanceFromBergen: 185,
    bestSeason: "May - September",
    coordinates: { lat: 61.2035, lng: 6.5295 },
    crowdLevel: "Low Crowds",
    images: [
      WM("Balestrand_Norway.jpg"),
      WM("Kviknes_Hotel_Balestrand.jpg"),
      WM("Balestrand_village_norway.jpg"),
      WM("Sognefjord_norway.jpg"),
      WM("Balestrand_fjord.jpg"),
    ],
    priority: "Highly Recommended",
    zone: "Sognefjord",
    driveFromBergen: "3h N",
    familyRating: "⭐⭐⭐⭐",
    highlights: [
      "Kviknes Hotel (1877) — one of Norway's grandest historic hotels",
      "Viking burial mounds in the village centre",
      "Apple orchards — foraging culture in early summer",
      "Very calm — almost no cruise ships",
    ],
  },
  {
    id: "fjaerland",
    name: "Fjærland — Book Town & Glacier View",
    shortDescription: "Norway's only book town at the end of the Fjærlandsfjord — drive within metres of the Bøyabreen glacier tongue.",
    longDescription:
      "Norway's only 'book town' at the end of the Fjærlandsfjord. Secondhand bookshops in old farm buildings, and you can drive within metres of the Bøyabreen glacier tongue. Atmospheric and completely un-touristy.",
    category: "Nature",
    distanceFromBergen: 210,
    bestSeason: "May - September",
    coordinates: { lat: 61.4154, lng: 6.7521 },
    crowdLevel: "Low Crowds",
    images: [
      WM("Fjærland_norway.jpg"),
      WM("Boyabreen_glacier_Fjærland.jpg"),
      WM("Fjærlandsfjord.jpg"),
      WM("Fjærland_booktown.jpg"),
      WM("Bøyabreen.jpg"),
    ],
    priority: "Nice to Have",
    zone: "Sognefjord",
    driveFromBergen: "3h N",
    familyRating: "⭐⭐⭐",
    highlights: [
      "Bøyabreen glacier arm — drive within metres of the ice",
      "Norwegian Book Town — secondhand bookshops in old farm buildings",
      "Very remote, end-of-the-road feeling",
      "Good morning stop before pushing north",
    ],
  },
  {
    id: "nigardsbreen",
    name: "Nigardsbreen Glacier — Blue Ice Walk",
    shortDescription: "The most family-accessible glacier in Norway — blue ice caves, towers and crevasses. Open from age 6.",
    longDescription:
      "The most family-accessible glacier arm in Norway. Guided blue-ice walks include caves, towers and crevasses. A short boat trip crosses the glacial lake to the trail start. Open to children from age 6 — check with guides for age 5.",
    category: "Glacier",
    distanceFromBergen: 225,
    bestSeason: "June - September",
    coordinates: { lat: 61.6897, lng: 7.1858 },
    crowdLevel: "Moderate",
    images: [
      WM("Nigardsbreen.jpg"),
      WM("Nigardsbreen_glacier_hike.jpg"),
      WM("Nigardsbreen_blue_ice.jpg"),
      WM("Jostedalsbreen_National_Park.jpg"),
      WM("Nigardsbreen_lake.jpg"),
    ],
    priority: "Must Do",
    zone: "Sognefjord",
    driveFromBergen: "3.5h N via Luster",
    familyRating: "⭐⭐⭐⭐⭐",
    highlights: [
      "Blue ice caves and towers — completely surreal landscape",
      "Jostedalen Breførarlag guides — all equipment provided",
      "Short boat trip from car park across glacial lake",
      "Check minimum age policy — usually 6+, ask about age 5",
    ],
  },
  {
    id: "urnes-stave-church",
    name: "Urnes Stave Church — UNESCO",
    shortDescription: "Norway's oldest stave church (12th century) — UNESCO listed, reached by a tiny foot ferry from Solvorn.",
    longDescription:
      "Norway's oldest stave church (12th century), UNESCO-listed. Reached by a tiny foot ferry from Solvorn village — the ferry crossing is itself an attraction for kids.",
    category: "Cultural",
    distanceFromBergen: 230,
    bestSeason: "May - September",
    coordinates: { lat: 61.2989, lng: 7.3174 },
    crowdLevel: "Low Crowds",
    images: [
      WM("Urnes_Stave_Church.jpg"),
      WM("Urnes_stavkirke.jpg"),
      WM("Lustrafjord_norway.jpg"),
      WM("Urnes_church_interior.jpg"),
      WM("Solvorn_Norway.jpg"),
    ],
    priority: "Nice to Have",
    zone: "Sognefjord",
    driveFromBergen: "3.5h N via Lustrafjord",
    familyRating: "⭐⭐⭐",
    highlights: [
      "Norway's oldest stave church — 12th century UNESCO World Heritage",
      "Celtic art, Viking carvings and Romanesque details in one building",
      "Small foot ferry from Solvorn — kids love the crossing",
      "Hilltop position with beautiful Lustrafjord views",
    ],
  },
  {
    id: "loen-skylift",
    name: "Loen Skylift — Gondola to 1011m",
    shortDescription: "One of the world's steepest gondolas — fjord level to 1,011m in under 5 minutes.",
    longDescription:
      "One of the world's steepest gondolas — fjord level to 1,011m in under 5 minutes. The 210-degree panorama spans Nordfjord, Lake Lovatnet and Jostedalsbreen glacier. The Hoven Restaurant at the top is excellent.",
    category: "Adventure",
    distanceFromBergen: 240,
    bestSeason: "April - October",
    coordinates: { lat: 61.8697, lng: 6.8446 },
    crowdLevel: "Moderate",
    images: [
      WM("Loen_Skylift.jpg"),
      WM("Loen_skylift_view.jpg"),
      WM("Mount_Hoven_Loen.jpg"),
      WM("Nordfjord_from_Loen_skylift.jpg"),
      WM("Loen_village_Norway.jpg"),
    ],
    priority: "Must Do",
    zone: "Nordfjord",
    driveFromBergen: "3.5h N",
    familyRating: "⭐⭐⭐⭐⭐",
    highlights: [
      "Fjord level to 1011m in 5 minutes — one of the steepest in the world",
      "210° panorama: fjord, glacier, mountains",
      "Hoven Restaurant at the top with local food",
      "Easy walks at the summit — fine for a 5-year-old",
    ],
  },
  {
    id: "lovatnet",
    name: "Lake Lovatnet — Turquoise Glacial Lake",
    shortDescription: "A glacially-fed lake of almost unreal turquoise colour — completely free to visit.",
    longDescription:
      "A glacially-fed lake of almost unreal turquoise colour. Completely free — just park and stare. Boat trips available to the inner end. The dramatic 1904 and 1936 rockfall story adds a haunting backstory.",
    category: "Nature",
    distanceFromBergen: 240,
    bestSeason: "May - September",
    coordinates: { lat: 61.8532, lng: 6.9064 },
    crowdLevel: "Low Crowds",
    images: [
      WM("Lovatnet.jpg"),
      WM("Lovatnet_turquoise_lake.jpg"),
      WM("Lovatnet_Lodalen.jpg"),
      WM("Lodalen_norway.jpg"),
      WM("Loen_Lodalen_valley.jpg"),
    ],
    priority: "Highly Recommended",
    zone: "Nordfjord",
    driveFromBergen: "3.5h N",
    familyRating: "⭐⭐⭐⭐⭐",
    highlights: [
      "Electric turquoise colour — glacier meltwater effect",
      "MS Kjenndal boat trips to the inner lake end",
      "Completely free — no fees, just park and enjoy",
      "Excellent spot for a lakeside lunch",
    ],
  },
  {
    id: "briksdalsbreen",
    name: "Briksdalsbreen Glacier + Troll Cars",
    shortDescription: "An arm of Jostedalsbreen reached via a spectacular valley, with electric troll cars carrying you up.",
    longDescription:
      "An arm of Jostedalsbreen reached through a spectacular valley. Electric 'troll cars' carry you most of the way up — perfect for young children. The valley itself, with waterfalls and sheer walls, is worth the trip alone.",
    category: "Glacier",
    distanceFromBergen: 265,
    bestSeason: "May - September",
    coordinates: { lat: 61.6745, lng: 6.8708 },
    crowdLevel: "Moderate",
    images: [
      WM("Briksdalsbreen.JPG"),
      WM("Briksdalsbreen_glacier_Norway.jpg"),
      WM("Briksdalen_valley.jpg"),
      WM("Briksdalsbreen_troll_car.jpg"),
      WM("Oldedalen_Norway.jpg"),
    ],
    priority: "Highly Recommended",
    zone: "Nordfjord",
    driveFromBergen: "4h N via Olden",
    familyRating: "⭐⭐⭐⭐",
    highlights: [
      "Troll cars (electric open-air vehicles) carry you most of the way up",
      "3km valley walk through waterfalls and mountain walls",
      "Glacier viewpoint — blue ice visible from below",
      "Book troll cars in advance in June",
    ],
  },
  {
    id: "alesund",
    name: "Ålesund — Art Nouveau City",
    shortDescription: "Norway's most architecturally striking city — rebuilt entirely in Art Nouveau style after a 1904 fire.",
    longDescription:
      "Norway's most architecturally striking city — rebuilt entirely in Art Nouveau style after a 1904 fire. The 418-step Aksla viewpoint delivers one of the best urban panoramas in Norway. The aquarium is one of Norway's best for families.",
    category: "Cultural",
    distanceFromBergen: 290,
    bestSeason: "Year-round",
    coordinates: { lat: 62.4722, lng: 6.1549 },
    crowdLevel: "Moderate",
    images: [
      WM("Ålesund_Norway.jpg"),
      WM("Aalesund_from_Aksla.jpg"),
      WM("Ålesund_art_nouveau.jpg"),
      WM("Aksla_viewpoint_Aalesund.jpg"),
      WM("Ålesund_harbour.jpg"),
    ],
    priority: "Highly Recommended",
    zone: "Ålesund & Hidden Fjords",
    driveFromBergen: "4.5h N",
    familyRating: "⭐⭐⭐⭐",
    highlights: [
      "Aksla viewpoint — 418 steps (or drive up) for sweeping city & fjord panorama",
      "Art Nouveau Centre — story of the 1904 rebuilding",
      "Atlanterhavsparken Aquarium — great for kids",
      "Excellent fresh seafood restaurants at the harbour",
    ],
  },
  {
    id: "hjorundfjord",
    name: "Hjørundfjord — Norway's Secret Fjord",
    shortDescription: "Same drama as Geirangerfjord with almost no tourists — the Sunnmøre Alps rise straight from the water.",
    longDescription:
      "Often called Norway's secret fjord — identical drama to Geiranger with almost no tourists. The Sunnmøre Alps rise sharply from the water. Hotel Union Øye (1891) is one of Norway's most atmospheric historic hotels.",
    category: "Fjord",
    distanceFromBergen: 290,
    bestSeason: "May - September",
    coordinates: { lat: 62.1278, lng: 6.5847 },
    crowdLevel: "Low Crowds",
    images: [
      WM("Hjørundfjord.jpg"),
      WM("Hjørundfjord_Norway.jpg"),
      WM("Sæbø_Hjørundfjord.jpg"),
      WM("Hotel_Union_Øye.jpg"),
      WM("Sunnmøre_Alps_Norway.jpg"),
    ],
    priority: "Highly Recommended",
    zone: "Ålesund & Hidden Fjords",
    driveFromBergen: "4.5h N",
    familyRating: "⭐⭐⭐⭐⭐",
    highlights: [
      "Same drama as Geirangerfjord — almost zero crowds",
      "Sunnmøre Alps peak directly from the water",
      "Villages of Sæbø, Urke, Øye — each has its own character",
      "Hotel Union Øye (1891) — worth a coffee stop",
    ],
  },
  {
    id: "norangsdalen",
    name: "Norangsdalen — The Queen Route",
    shortDescription: "One of Norway's most atmospheric valley drives — the 'Queen Route' with almost no tourists.",
    longDescription:
      "One of Norway's most atmospheric valley drives — squeezed between dramatic peaks, past summer mountain pastures at Urasetra, and a mysterious submerged ghost village under lake Lyngstøylsvatnet. Seven European queens have passed through.",
    category: "Scenic Drive",
    distanceFromBergen: 315,
    bestSeason: "June - September",
    coordinates: { lat: 62.1469, lng: 6.8012 },
    crowdLevel: "Low Crowds",
    images: [
      WM("Norangsdalen.jpg"),
      WM("Norangsdalen_valley_Norway.jpg"),
      WM("Lyngstøylsvatnet.jpg"),
      WM("Norangsdalen_road.jpg"),
      WM("Hjørundfjord.jpg"),
    ],
    priority: "Highly Recommended",
    zone: "Ålesund & Hidden Fjords",
    driveFromBergen: "5h N (connector valley)",
    familyRating: "⭐⭐⭐⭐⭐",
    vanNote: "⚠️ Very narrow road — go slowly, fine for a 5.4m campervan",
    highlights: [
      "'The Queen Route' — Queen Sonja hikes here regularly",
      "Urasetra summer pastures — Alpine meadows, grazing cattle",
      "Lyngstøylsvatnet — lake with submerged village visible",
      "Virtually no tourists — a true hidden route",
    ],
  },
  {
    id: "geirangerfjord",
    name: "Geirangerfjord + Seven Sisters",
    shortDescription: "UNESCO-listed — possibly the most dramatic fjord in Norway. The Seven Sisters waterfall is unmissable.",
    longDescription:
      "UNESCO-listed and possibly the most dramatic fjord in Norway. The Seven Sisters — seven streams falling simultaneously — are best seen from a fjord boat. Despite the cruise crowds, it's worth every minute.",
    category: "Fjord",
    distanceFromBergen: 350,
    bestSeason: "May - September",
    coordinates: { lat: 62.1044, lng: 7.0853 },
    crowdLevel: "Popular",
    images: [
      WM("Geirangerfjord.jpg"),
      WM("Seven_Sisters_Waterfall_in_Geirangerfjord,_Norway.JPG"),
      WM("Geiranger_village_fjord.jpg"),
      WM("Geirangerfjord_Norway.jpg"),
      WM("De_syv_søstre_Geiranger.jpg"),
    ],
    priority: "Must Do",
    zone: "Geirangerfjord",
    driveFromBergen: "5h N",
    familyRating: "⭐⭐⭐⭐⭐",
    highlights: [
      "Seven Sisters waterfall — seven streams cascading in parallel",
      "Fjord boat from Geiranger village — see the falls up close",
      "Geiranger campsite above the village for fjord views",
      "⚠️ 1 million visitors/year — up to 180 cruise ships per summer",
    ],
  },
  {
    id: "ornesvingen",
    name: "Ørnesvingen — Eagle Road Viewpoint",
    shortDescription: "The iconic bird's-eye view of Geirangerfjord — 9 hairpin bends descend to the village below.",
    longDescription:
      "The iconic bird's-eye view of Geirangerfjord — 9 dramatic hairpin bends descend from this viewpoint to the village below. The classic Norway postcard shot. No hiking required.",
    category: "Viewpoint",
    distanceFromBergen: 350,
    bestSeason: "May - October",
    coordinates: { lat: 62.1347, lng: 7.0697 },
    crowdLevel: "Popular",
    images: [
      WM("Ornesvingen.jpg"),
      WM("Eagle_road_Geiranger.jpg"),
      WM("Ørnesvingen_viewpoint.jpg"),
      WM("Geirangerfjord_from_Eagle_Road.jpg"),
      WM("Geirangerfjord.jpg"),
    ],
    priority: "Must Do",
    zone: "Geirangerfjord",
    driveFromBergen: "5h N (above Geiranger)",
    familyRating: "⭐⭐⭐⭐⭐",
    vanNote: "⚠️ Eagle Road descent is steep with tight bends — use low gear",
    highlights: [
      "The iconic bird's-eye viewpoint of Geirangerfjord",
      "Eagle Road descends on 9 tight hairpin bends to Geiranger",
      "No hiking — 2-minute walk from car park",
      "⚠️ Car park is small — arrive early or late afternoon",
    ],
  },
  {
    id: "dalsnibba",
    name: "Dalsnibba / Geiranger Skywalk",
    shortDescription: "Europe's highest roadside viewpoint at 1,476m — look almost straight down onto Geirangerfjord.",
    longDescription:
      "Europe's highest roadside viewpoint at 1,476m — look almost straight down onto Geirangerfjord. Toll road (~200 NOK). Can be cold or snowy in early June at this altitude.",
    category: "Viewpoint",
    distanceFromBergen: 355,
    bestSeason: "June - September",
    coordinates: { lat: 62.0697, lng: 7.2758 },
    crowdLevel: "Moderate",
    images: [
      WM("Dalsnibba_Geirangerfjord.jpg"),
      WM("Geiranger_skywalk_Dalsnibba.jpg"),
      WM("Dalsnibba_Norway.jpg"),
      WM("Geirangerfjord_from_Dalsnibba.jpg"),
      WM("Geirangerfjord.jpg"),
    ],
    priority: "Nice to Have",
    zone: "Geirangerfjord",
    driveFromBergen: "5h+ N (toll road)",
    familyRating: "⭐⭐⭐⭐",
    highlights: [
      "1,476m altitude — look down onto the fjord from near snowline",
      "Europe's highest roadside viewpoint",
      "Toll road — worth it on a clear day",
      "⚠️ Can be cold, foggy or have snow in early June",
    ],
  },
  {
    id: "trollstigen",
    name: "Trollstigen — 11 Hairpin Bends",
    shortDescription: "Eleven dramatic hairpin bends on one of the world's most iconic roads. Open in 2026 after major repairs.",
    longDescription:
      "Eleven dramatic hairpin bends spiralling up a sheer mountain face — one of the world's most iconic roads. Stigfossen waterfall is crossed by a bridge mid-climb. Confirmed open in 2026 after major repairs.",
    category: "Scenic Drive",
    distanceFromBergen: 340,
    bestSeason: "May - October",
    coordinates: { lat: 62.4558, lng: 7.6681 },
    crowdLevel: "Popular",
    images: [
      WM("Trollstigen.jpg"),
      WM("Trollstigen_Norway_2006.JPG"),
      WM("Trollstigen_hairpin.jpg"),
      WM("Stigfossen_Trollstigen.jpg"),
      WM("Trollstigen_road.jpg"),
    ],
    priority: "Must Do",
    zone: "Trollstigen & Åndalsnes",
    driveFromBergen: "5h N",
    familyRating: "⭐⭐⭐⭐⭐",
    vanNote: "⚠️ Narrow road — your 5.4m camper can do it, go slowly and watch for buses",
    highlights: [
      "11 hairpin bends ascending 858m — the drive IS the attraction",
      "Stigfossen waterfall — crossed by a bridge on the ascent",
      "Viewpoint platform + café at the top",
      "⚠️ Up to 2,000 vehicles/day — start by 7am",
      "✅ Confirmed open in 2026 from mid-May",
    ],
  },
  {
    id: "andalsnes-trollveggen",
    name: "Åndalsnes + Trollveggen (Troll Wall)",
    shortDescription: "Europe's tallest vertical rock face at 1,000m — visible right from the road driving into Romsdalen valley.",
    longDescription:
      "Trollveggen — Europe's tallest vertical rock face at 1,000m — is visible right from the road driving into Romsdalen valley. Åndalsnes is calm, well-equipped, and perfectly positioned for the Golden Route.",
    category: "Nature",
    distanceFromBergen: 345,
    bestSeason: "May - October",
    coordinates: { lat: 62.5647, lng: 7.6875 },
    crowdLevel: "Low Crowds",
    images: [
      WM("Trollveggen.jpg"),
      WM("Andalsnes_Norway.jpg"),
      WM("Romsdalen_valley.jpg"),
      WM("Trollveggen_Norway.jpg"),
      WM("Romsdalsfjord_Åndalsnes.jpg"),
    ],
    priority: "Highly Recommended",
    zone: "Trollstigen & Åndalsnes",
    driveFromBergen: "5h N",
    familyRating: "⭐⭐⭐⭐",
    highlights: [
      "Trollveggen (Troll Wall) — 1,000m vertical rock face, visible from the road",
      "Romsdalen valley drive — sheer mountain walls on both sides",
      "Good campervan stopover facilities",
      "Base for the 'Golden Route' to Trollstigen and Geiranger",
    ],
  },
]
